require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/cash_transactions", type: :request do
  # This should return the minimal set of attributes required to create a valid
  # CashTransaction. As you add validations to CashTransaction, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the headers
  # in order to pass any filters (e.g. authentication) defined in
  # CashTransactionsController, or in your router and rack
  # middleware. Be sure to keep this updated too.
  let(:valid_headers) {
    {}
  }

  describe "GET /index" do
    it "renders a successful response" do
      CashTransaction.create! valid_attributes
      get cash_transactions_url, headers: valid_headers, as: :json
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      cash_transaction = CashTransaction.create! valid_attributes
      get cash_transaction_url(cash_transaction), as: :json
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new CashTransaction" do
        expect {
          post cash_transactions_url,
               params: { cash_transaction: valid_attributes }, headers: valid_headers, as: :json
        }.to change(CashTransaction, :count).by(1)
      end

      it "renders a JSON response with the new cash_transaction" do
        post cash_transactions_url,
             params: { cash_transaction: valid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:created)
        expect(response.content_type).to match(a_string_including("application/json"))
      end
    end

    context "with invalid parameters" do
      it "does not create a new CashTransaction" do
        expect {
          post cash_transactions_url,
               params: { cash_transaction: invalid_attributes }, as: :json
        }.to change(CashTransaction, :count).by(0)
      end

      it "renders a JSON response with errors for the new cash_transaction" do
        post cash_transactions_url,
             params: { cash_transaction: invalid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:unprocessable_entity)
        expect(response.content_type).to match(a_string_including("application/json"))
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested cash_transaction" do
        cash_transaction = CashTransaction.create! valid_attributes
        patch cash_transaction_url(cash_transaction),
              params: { cash_transaction: new_attributes }, headers: valid_headers, as: :json
        cash_transaction.reload
        skip("Add assertions for updated state")
      end

      it "renders a JSON response with the cash_transaction" do
        cash_transaction = CashTransaction.create! valid_attributes
        patch cash_transaction_url(cash_transaction),
              params: { cash_transaction: new_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:ok)
        expect(response.content_type).to match(a_string_including("application/json"))
      end
    end

    context "with invalid parameters" do
      it "renders a JSON response with errors for the cash_transaction" do
        cash_transaction = CashTransaction.create! valid_attributes
        patch cash_transaction_url(cash_transaction),
              params: { cash_transaction: invalid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:unprocessable_entity)
        expect(response.content_type).to match(a_string_including("application/json"))
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested cash_transaction" do
      cash_transaction = CashTransaction.create! valid_attributes
      expect {
        delete cash_transaction_url(cash_transaction), headers: valid_headers, as: :json
      }.to change(CashTransaction, :count).by(-1)
    end
  end
end
